# Generated by Django 3.2.16 on 2023-02-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor_products',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='other_products',
            name='date',
            field=models.DateField(),
        ),
    ]
