# Generated by Django 3.2.16 on 2023-02-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20230205_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor_products',
            name='hp',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
