# Generated by Django 3.2.16 on 2023-02-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_motor_products_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor_products',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='other_products',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
