# Generated by Django 3.2.16 on 2023-02-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='selled_motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('hp', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hsncode', models.CharField(max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('others', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phno', models.IntegerField(max_length=10)),
                ('customer_address', models.TextField()),
            ],
        ),
    ]
