# Generated by Django 3.2.16 on 2023-02-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selled_motor',
            name='customer_phno',
            field=models.IntegerField(),
        ),
    ]
