# Generated by Django 3.2.16 on 2023-02-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_selled_motor_customer_phno'),
    ]

    operations = [
        migrations.AddField(
            model_name='selled_motor',
            name='dateandtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
