# Generated by Django 3.2.16 on 2023-02-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_selled_motor_dateandtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selled_motor',
            name='dateandtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
