# Generated by Django 3.2.16 on 2023-02-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_selled_motor_dateandtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='selled_other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('specifications', models.CharField(max_length=50)),
                ('hsncode', models.CharField(max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phno', models.IntegerField()),
                ('customer_address', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
